version: '3.8'

services:
    nginx:
        image: nginx:latest
        container_name: social_nginx
        restart: always
        volumes:
            - ./:/var/www
            - ./_docker/nginx:/etc/nginx/conf.d
        ports:
            - 8000:80
        depends_on:
            - app
            - db
            - node

    app:
        container_name: social_app
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - db
            - node

    db:
        image: mysql:8.0
        container_name: social_db
        restart: always
        volumes:
            - ./_docker/mysql_data:/var/lib/mysql
        env_file:
            - ./_docker/env/mysql.env
        ports:
            - 3316:3306
        command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci

    phpmyadmin:
        image: phpmyadmin
        container_name: social_phpmyadmin
        restart: always
        ports:
            - 8080:80
        env_file:
            - ./_docker/env/phpmyadmin.env
        depends_on:
            - db

    node:
        image: node
        container_name: social_node
        ports:
            - 3000:3000
        volumes:
            - ./:/var/www
        working_dir: /var/www
        # tty подключает потоковый ввод, вывод из контейнера
        tty: true
